baseurl = "https://example.com"
languageCode = "nl"
title = "KC Dordrecht"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/briangorter078\">Brian Gorter</a> 2017"
disqusShortname = "shortname"
googleAnalytics = "UA-91629503-1"
description = "Your personal description"
keywords = ["KC Dordrecht", "Blog"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/briangorter078"
fa_icon = "fa-github"
